[package]
name = "photobridge-pixel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
little_exif = "=0.6.23"
photobridge-core.workspace = true
quick-xml = "0.38"
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
